"""`analysis-video install-skill` — 에이전트가 이 도구를 찾아 쓰게 만드는 설치 지점.

설치돼 있어도 에이전트가 존재를 모르면 쓰이지 않는다. 그 발견 경로를 심는 것이
이 모듈이고, 두 형태를 지원한다:

- Claude Code: `~/.claude/skills/analysis-video/SKILL.md` (개인 스킬 — 등록부도
  설정 수정도 필요 없다. 파일 하나면 모든 프로젝트에서 로드된다)
- 그 밖의 하네스(Codex·Cline·Cursor 등): 규칙 파일에 `agent-guide` 전문을
  마커 구간으로 삽입 (`--agents-file AGENTS.md`)

**SKILL.md에 사용법 본문을 복사하지 않는다.** 짧은 안내와 "`agent-guide`를 실행해
그 출력을 따르라"만 둔다. 복사하면 패키지 업그레이드와 스킬 갱신이 따로 일어나
두 문서가 서로 다른 기본값을 주장하게 되는데, 이 저장소의 README가 이미 제거된
플래그를 안내하며 그 고장을 한 번 겪었다. 정본은 agent_guide.py 하나로 남긴다.
**숫자도 같은 이유로 두지 않는다** — render_skill 독스트링 참조.

저장소 루트의 SKILL.md도 손으로 쓴 사본이 아니라 `render_skill(__version__)`의
**생성물**이다(발견 채널 — `npx skills add owner/repo` 계열 도구와 스킬 디렉터리
사이트가 공개 저장소 루트의 그 파일을 긁는다). 만드는 법은 그 파일 머리말과
docs/RELEASING.md에 적혀 있고, ci.yml의 `루트 SKILL.md 가 생성 결과와 같은가`
잡이 이 템플릿의 렌더 결과와 대조한다.

부수효과(사용자 홈에 파일 쓰기)가 있으므로 다른 명령이 이걸 몰래 하지 않는다 —
명시적으로 이 커맨드를 불러야만 실행된다. 쓰기는 전부 manifest.write_text_atomic
(임시 파일 + os.replace)에 위임한다: 남의 규칙 파일과 사용자 홈을 덮어쓰는
자리라 반쯤 쓰인 파일을 남기면 안 된다.
"""
import os
import re
from pathlib import Path

from .errors import EXIT_INPUT, CliError
from .manifest import write_text_atomic

SKILL_NAME = "analysis-video"

# 마커에 버전을 넣지 않는다 — 넣으면 다음 버전에서 구간을 못 찾아 중복 삽입된다.
# 버전은 구간 안에 적어 두어 무엇으로 생성됐는지만 남긴다.
_BEGIN = f"<!-- {SKILL_NAME}:agent-guide BEGIN (생성됨 — 직접 수정하지 마세요) -->"
_END = f"<!-- {SKILL_NAME}:agent-guide END -->"

_SKILL_TEMPLATE = """\
---
# Generated by `analysis-video install-skill` — do not edit by hand.
# Source of truth: packages/core/src/analysis_video/skill.py (_SKILL_TEMPLATE,
# rendered by render_skill) in https://github.com/hwanyong/analysis-video.
# Both copies of this file — the one in the repository root and the one in
# ~/.claude/skills/analysis-video/ — are products of that template, so an edit
# made here is lost on the next install. Change the template instead.
# Regenerate the installed copy: `analysis-video install-skill`
# Regenerate the copy in the repository root:
#   uv run --package analysis-video analysis-video install-skill --dir "$(mktemp -d)"
#   then copy the file its JSON `path` points at over the root SKILL.md.
name: analysis-video
description: >
  Turn a slide-based or lecture video into something an agent can read: one
  section per on-screen state with its image(s), the seconds it was shown, and
  what was said. Use when the user gives a video file path or asks to analyse,
  summarise, or pull slides/notes out of a lecture or screen recording.
  한국어 트리거: 영상 분석, 강의 영상, 슬라이드 추출, 영상 정리, 자막·대사 정리.
---

# analysis-video

Produces `context.md`: screens, their images, their time ranges, and the
dialogue spoken during each. That file is what you read.

Generated by analysis-video @VERSION@. Re-run `analysis-video install-skill`
after upgrading if this file ever needs refreshing.

## How to invoke it

Use `analysis-video …` if it is on PATH; otherwise `uvx analysis-video@latest …`
(same thing, no install). Keep the `@latest`: uvx caches the version it resolved
the first time and keeps running that one, so without it you stay pinned to
whatever was current the day this machine first ran the tool. If neither
`analysis-video` nor `uv` exists, tell the user to install uv
(https://docs.astral.sh/uv/) and stop — do not try to install anything yourself.

## Start here, every time

1. `analysis-video agent-guide` — **the authoritative usage document.** Run it
   and follow what it says. Every command, flag, default, exit code and output
   path is in there, injected from the real constants. Do not guess flags from
   memory; do not rely on this file for them.
2. `analysis-video status <video>` — where this video stands and what to do
   next. Safe to call on a video that was never analysed. Its `next` field is
   the loop below.

## The loop: keep going until `next.do` is `done`

Analysing a video is **not** finished when `context.md` exists. That file is the
material; the analysis is what you write from it, and this tool keeps a place
for it so it survives the session. Every result carries a `next` object:

- `next.do == "run"` — run `next.command` verbatim, then read the new `next`.
- `next.do == "read"` — open the files in `next.read`, then pipe your analysis
  into `next.command` (it ends in `review --write -`). Write it for a reader who
  has not seen the video.
- `next.do == "done"` — now answer the user.

Stopping at `read` leaves the work unrecorded: the next session finds no
analysis and pays for every image again. `review` is one command; run it.

## Budget: images are the expensive part, not the text

`next.cost` tells you how many images `context.md` points at and roughly what
they cost. Those are already downscaled read copies. If the cost does not fit
your context window:

- **First, open fewer images.** Each entry in `context.md` prints the seconds
  its screen was on display — the long ones carry more.
- **Then re-detect more coarsely** with `--cut-area-threshold` on `analyze`.
  That flag is the one dial that trades images for detail. **Take its default
  and the value to raise it to from `agent-guide`, never from this file** — it
  prints them from the constants the detector actually runs on, and it says what
  the trade costs you. This file is a snapshot of the day it was installed.
- **Never raise `--rate-threshold` to save images — it produces *more*.** That
  value also decides when a screen has settled, so raising it captures earlier,
  busier moments. Raising `--anchor-threshold` is a bad trade too: it saves
  little and drops screens you would have wanted.

Re-detecting rewrites `context.md`, so any review written against the old one is
marked stale and `next` will ask for it again. Decide the threshold before you
read, not after.

An analysis directory is larger than the video it came from, and nothing prunes
it for you. `analysis-video clean <video>` reports what is in there and what can
go; with `--level` it removes it. Your review, the transcript and the reading
copies are never touched by it. Mention this if the user cares about disk.

## Non-negotiables

- **Only the video the user named.** `<video>` is a path to a local file. This
  tool fetches no video and opens no URL. If the file is not on disk, ask for it
  and stop — do not go hunting the filesystem for something that looks close.
- **stdout is one JSON object; branch on the exit code.** stderr is progress
  log for humans — never parse it.
- **Use the paths the JSON gives you.** They are absolute, so you may run from
  any working directory. Read the `context.md` it points at; `metadata.json` is
  an audit record, not something to read end to end.
- **Environment trouble is exit 4.** `analysis-video doctor` diagnoses it and
  takes no arguments. Report its `error.hint` rather than working around it.
  `doctor` lists capabilities and exits 0 whenever the tool can run at all — an
  absent speech-recognition backend is `available: false`, not a fault, because
  a video that carries its own subtitles never needs one.
"""


def _skills_root() -> Path:
    """Claude Code 개인 스킬 디렉터리. CLAUDE_CONFIG_DIR을 존중한다."""
    configured = os.environ.get("CLAUDE_CONFIG_DIR")
    base = Path(configured).expanduser() if configured else Path.home() / ".claude"
    return base / "skills"


def render_skill(version: str) -> str:
    """템플릿에 버전만 박아 돌려준다. 주입 토큰이 `@VERSION@` 하나인 것이 이 함수의
    지금 모습이고, 그게 맞다.

    한때 여기서 컷 면적 기본값·권장값도 상수에서 주입했다. 정본은 하나라는 원칙은
    지켰지만 전제가 틀렸다 — **SKILL.md는 설치 시점의 스냅샷이고, 갱신 트리거도
    낡음 경고도 없다.** 주입은 렌더되는 그 순간의 값만 맞춰 줄 뿐, 파일이 사용자
    홈에 놓인 다음의 표류는 막지 못한다. 실제로 컷 면적 기본값은 최근 여섯 커밋에서
    네 번 움직였고(0.04→0.02→0.01→0.005→0.002) 버전은 0.1.0 그대로였다. 즉 낡는
    주기와 재설치 주기가 무관하다.

    그래서 숫자는 전부 뺐고 SKILL.md는 정성적 지침만 남긴다. 값은 `agent-guide`가
    준다 — 그것은 분석을 실제로 실행할 바로 그 프로그램에서 매번 렌더되므로 구조적
    으로 어긋날 수 없다. 버전만 남긴 이유는 반대다: 그 한 줄은 스냅샷이라는 사실
    자체를 기록하는 값이라, 낡아 있는 것이 곧 정보다(어느 버전이 쓴 파일인가)."""
    return _SKILL_TEMPLATE.replace("@VERSION@", version)


def install_claude_skill(version: str, root: Path | None = None) -> dict:
    """SKILL.md를 쓰고 무엇을 어디에 썼는지 돌려준다. 멱등 — 같은 내용이면 안 쓴다."""
    target_root = (root.expanduser() if root is not None else _skills_root()).resolve()
    path = target_root / SKILL_NAME / "SKILL.md"
    body = render_skill(version)

    previous = path.read_text(encoding="utf-8") if path.exists() else None
    if previous == body:
        return {"target": "claude-skill", "path": str(path), "action": "unchanged"}

    path.parent.mkdir(parents=True, exist_ok=True)
    write_text_atomic(path, body)
    return {"target": "claude-skill", "path": str(path),
            "action": "updated" if previous is not None else "created"}


def _marker_offsets(text: str, marker: str) -> list[int]:
    """마커가 나타난 문자 오프셋 전부. `in` 검사가 아니라 개수를 세는 이유는
    install_agents_file 독스트링에 있다."""
    return [m.start() for m in re.finditer(re.escape(marker), text)]


def _line_of(text: str, offset: int) -> int:
    """오프셋의 줄 번호(1부터). 사용자가 편집기에서 바로 그 줄로 갈 수 있게."""
    return text.count("\n", 0, offset) + 1


def install_agents_file(path: Path, version: str, guide: str) -> dict:
    """규칙 파일(AGENTS.md 등)의 마커 구간을 교체한다 — 없으면 끝에 덧붙인다.

    `agent-guide >> AGENTS.md`가 멱등이 아니라는 문제를 여기서 없앤다: 추가 연산은
    업그레이드마다 사용법 전문을 중복 누적시키고, 그러면 한 파일 안의 두 사본이
    서로 다른 기본값을 주장한다.

    **마커가 1:1로 짝을 이루지 않으면 아무것도 쓰지 않고 exit 2로 알린다.** 예전에는
    둘 다 있을 때만 구간을 교체하고 한쪽만 있으면 덧붙였는데, 그 조합이 사용자 문서를
    지웠다(재현 완료). BEGIN만 남은 파일에 한 번 설치하면 BEGIN 2 / END 1이 되고,
    그 다음 실행의 정규식(`BEGIN.*?END`, DOTALL·non-greedy)이 **첫 BEGIN부터 유일한
    END까지**를 한 덩어리로 보아 그 사이의 사용자 문장을 생성 블록으로 덮어썼다.
    남의 규칙 파일이므로 어긋난 마커를 추측해서 고치지 않는다 — 무엇이 몇 번째 줄에
    몇 개 있는지 돌려주고 사람이 고르게 한다. 짝이 맞으면 교체는 정규식이 아니라
    오프셋 잘라내기로 한다(치환 문자열의 역슬래시가 re.sub의 이스케이프로 해석되는
    사고도 함께 사라진다)."""
    target = path.expanduser().resolve()
    block = f"{_BEGIN}\n<!-- analysis-video {version} -->\n\n{guide.strip()}\n\n{_END}\n"

    previous = target.read_text(encoding="utf-8") if target.exists() else None
    if previous is None:
        new, action = block, "created"
    else:
        begins = _marker_offsets(previous, _BEGIN)
        ends = _marker_offsets(previous, _END)
        if not begins and not ends:            # 아직 우리 구간이 없다 — 끝에 붙인다
            separator = "" if previous.endswith("\n\n") else \
                ("\n" if previous.endswith("\n") else "\n\n")
            new, action = previous + separator + block, "appended"
        elif len(begins) == len(ends) == 1 and begins[0] < ends[0]:   # 한 쌍 — 교체
            stop = ends[0] + len(_END)
            if previous[stop:stop + 1] == "\n":
                stop += 1
            new, action = previous[:begins[0]] + block + previous[stop:], "updated"
        else:                                  # 그 밖은 전부 거부 — 위 독스트링
            raise CliError(
                EXIT_INPUT, "agents-file-markers",
                f"{target}의 생성 구간 마커가 짝을 이루지 않습니다 "
                f"(BEGIN {len(begins)}개 / END {len(ends)}개). "
                "덮어쓰면 그 사이의 내용이 사라지므로 아무것도 쓰지 않았습니다.",
                hint="BEGIN과 END가 한 쌍씩, BEGIN이 먼저 오도록 고친 뒤 다시 "
                     "실행하세요. 생성 구간을 통째로 지우고 실행하면 파일 끝에 "
                     "새로 붙습니다.",
                details={
                    "begin": {"marker": _BEGIN, "count": len(begins),
                              "lines": [_line_of(previous, o) for o in begins]},
                    "end": {"marker": _END, "count": len(ends),
                            "lines": [_line_of(previous, o) for o in ends]},
                })

    if new == previous:
        return {"target": "agents-file", "path": str(target), "action": "unchanged"}

    target.parent.mkdir(parents=True, exist_ok=True)
    write_text_atomic(target, new)
    return {"target": "agents-file", "path": str(target), "action": action}
